// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.nwp.service;

public final class UserService {
  private UserService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_service.proto\022\017com.nwp.service\032\020u" +
      "ser_model.proto2K\n\017UserServiceGrpc\0228\n\010sa" +
      "yHello\022\023.com.nwp.model.User\032\027.com.nwp.mo" +
      "del.GreetingB\023\n\017com.nwp.serviceP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nwp.model.UserModel.getDescriptor(),
        }, assigner);
    com.nwp.model.UserModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
