// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_model.proto

package com.nwp.model;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nwp.model.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
