// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_model.proto

package com.nwp.model;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nwp.model.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
