/*
 * This file is generated by jOOQ.
 */
package com.example.grpcservice.user_info;


import com.example.grpcservice.user_info.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mydatabase
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mydatabase.user</code>.
     */
    public static final User USER = com.example.grpcservice.user_info.tables.User.USER;
}
